package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCuCorpInfo<M extends BaseCuCorpInfo<M>> extends Model<M> implements IBean {

	public void setCuCorpId(java.lang.String cuCorpId) {
		set("cu_corp_id", cuCorpId);
	}

	public java.lang.String getCuCorpId() {
		return get("cu_corp_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setLegalPerson(java.lang.String legalPerson) {
		set("legal_person", legalPerson);
	}

	public java.lang.String getLegalPerson() {
		return get("legal_person");
	}

	public void setConpanyType(java.lang.String conpanyType) {
		set("conpany_type", conpanyType);
	}

	public java.lang.String getConpanyType() {
		return get("conpany_type");
	}

	public void setConpanySize(java.lang.Integer conpanySize) {
		set("conpany_size", conpanySize);
	}

	public java.lang.Integer getConpanySize() {
		return get("conpany_size");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setFoundTime(java.lang.Integer foundTime) {
		set("found_time", foundTime);
	}

	public java.lang.Integer getFoundTime() {
		return get("found_time");
	}

	public void setYearIncome(java.math.BigDecimal yearIncome) {
		set("year_income", yearIncome);
	}

	public java.math.BigDecimal getYearIncome() {
		return get("year_income");
	}

	public void setBusiness(java.lang.String business) {
		set("business", business);
	}

	public java.lang.String getBusiness() {
		return get("business");
	}

}
