package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCuObjectCustomer<M extends BaseCuObjectCustomer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCuPossibleId(java.lang.String cuPossibleId) {
		set("cu_possible_id", cuPossibleId);
	}

	public java.lang.String getCuPossibleId() {
		return get("cu_possible_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setCardType(java.lang.String cardType) {
		set("card_type", cardType);
	}

	public java.lang.String getCardType() {
		return get("card_type");
	}

	public void setCardId(java.lang.String cardId) {
		set("card_id", cardId);
	}

	public java.lang.String getCardId() {
		return get("card_id");
	}

	public void setBelongUserId(java.lang.Integer belongUserId) {
		set("belong_user_id", belongUserId);
	}

	public java.lang.Integer getBelongUserId() {
		return get("belong_user_id");
	}

	public void setBelongUserName(java.lang.String belongUserName) {
		set("belong_user_name", belongUserName);
	}

	public java.lang.String getBelongUserName() {
		return get("belong_user_name");
	}

	public void setBelongOrgId(java.lang.String belongOrgId) {
		set("belong_org_id", belongOrgId);
	}

	public java.lang.String getBelongOrgId() {
		return get("belong_org_id");
	}

	public void setBelongOrgName(java.lang.String belongOrgName) {
		set("belong_org_name", belongOrgName);
	}

	public java.lang.String getBelongOrgName() {
		return get("belong_org_name");
	}

	public void setDlcatMemberId(java.lang.Integer dlcatMemberId) {
		set("dlcat_member_id", dlcatMemberId);
	}

	public java.lang.Integer getDlcatMemberId() {
		return get("dlcat_member_id");
	}

	public void setDlcatTrustAccount(java.lang.String dlcatTrustAccount) {
		set("dlcat_trust_account", dlcatTrustAccount);
	}

	public java.lang.String getDlcatTrustAccount() {
		return get("dlcat_trust_account");
	}

	public void setContactInfo(java.lang.String contactInfo) {
		set("contact_info", contactInfo);
	}

	public java.lang.String getContactInfo() {
		return get("contact_info");
	}

	public void setBelongPartnerId(java.lang.String belongPartnerId) {
		set("belong_partner_id", belongPartnerId);
	}

	public java.lang.String getBelongPartnerId() {
		return get("belong_partner_id");
	}

	public void setInputTime(java.lang.Integer inputTime) {
		set("input_time", inputTime);
	}

	public java.lang.Integer getInputTime() {
		return get("input_time");
	}

	public void setInputUserId(java.lang.Integer inputUserId) {
		set("input_user_id", inputUserId);
	}

	public java.lang.Integer getInputUserId() {
		return get("input_user_id");
	}

	public void setInputUserName(java.lang.String inputUserName) {
		set("input_user_name", inputUserName);
	}

	public java.lang.String getInputUserName() {
		return get("input_user_name");
	}

	public void setInputOrgId(java.lang.String inputOrgId) {
		set("input_org_id", inputOrgId);
	}

	public java.lang.String getInputOrgId() {
		return get("input_org_id");
	}

	public void setInputOrgName(java.lang.String inputOrgName) {
		set("input_org_name", inputOrgName);
	}

	public java.lang.String getInputOrgName() {
		return get("input_org_name");
	}

	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.Integer getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
	}

	public java.lang.Integer getUpdateUserId() {
		return get("update_user_id");
	}

	public void setUpdateUserName(java.lang.String updateUserName) {
		set("update_user_name", updateUserName);
	}

	public java.lang.String getUpdateUserName() {
		return get("update_user_name");
	}

	public void setUpdateOrgId(java.lang.String updateOrgId) {
		set("update_org_id", updateOrgId);
	}

	public java.lang.String getUpdateOrgId() {
		return get("update_org_id");
	}

	public void setUpdateOrgName(java.lang.String updateOrgName) {
		set("update_org_name", updateOrgName);
	}

	public java.lang.String getUpdateOrgName() {
		return get("update_org_name");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
