package com.dlcat.model;

import com.dlcat.base.BaseCuPossibleCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuPossibleCustomer extends BaseCuPossibleCustomer<CuPossibleCustomer> {
	public static final CuPossibleCustomer dao = new CuPossibleCustomer().dao();
}
