package com.dlcat.model;

import com.dlcat.base.BaseLoanBusinessCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanBusinessCategory extends BaseLoanBusinessCategory<LoanBusinessCategory> {
	public static final LoanBusinessCategory dao = new LoanBusinessCategory().dao();
}
