package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoanApplyApprove<M extends BaseLoanApplyApprove<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}

	public java.lang.Integer getCategoryId() {
		return get("category_id");
	}

	public void setLoanObjectType(java.lang.String loanObjectType) {
		set("loan_object_type", loanObjectType);
	}

	public java.lang.String getLoanObjectType() {
		return get("loan_object_type");
	}

	public void setCuId(java.lang.String cuId) {
		set("cu_id", cuId);
	}

	public java.lang.String getCuId() {
		return get("cu_id");
	}

	public void setCuName(java.lang.String cuName) {
		set("cu_name", cuName);
	}

	public java.lang.String getCuName() {
		return get("cu_name");
	}

	public void setCardType(java.lang.String cardType) {
		set("card_type", cardType);
	}

	public java.lang.String getCardType() {
		return get("card_type");
	}

	public void setCardId(java.lang.String cardId) {
		set("card_id", cardId);
	}

	public java.lang.String getCardId() {
		return get("card_id");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setPeriod(java.lang.Integer period) {
		set("period", period);
	}

	public java.lang.Integer getPeriod() {
		return get("period");
	}

	public void setApr(java.math.BigDecimal apr) {
		set("apr", apr);
	}

	public java.math.BigDecimal getApr() {
		return get("apr");
	}

	public void setRepayType(java.lang.Integer repayType) {
		set("repay_type", repayType);
	}

	public java.lang.Integer getRepayType() {
		return get("repay_type");
	}

	public void setLoanDec(java.lang.String loanDec) {
		set("loan_dec", loanDec);
	}

	public java.lang.String getLoanDec() {
		return get("loan_dec");
	}

	public void setLoanUse(java.lang.String loanUse) {
		set("loan_use", loanUse);
	}

	public java.lang.String getLoanUse() {
		return get("loan_use");
	}

	public void setFlowObjectNo(java.lang.String flowObjectNo) {
		set("flow_object_no", flowObjectNo);
	}

	public java.lang.String getFlowObjectNo() {
		return get("flow_object_no");
	}

	public void setFlowObjectName(java.lang.String flowObjectName) {
		set("flow_object_name", flowObjectName);
	}

	public java.lang.String getFlowObjectName() {
		return get("flow_object_name");
	}

	public void setNodeNo(java.lang.String nodeNo) {
		set("node_no", nodeNo);
	}

	public java.lang.String getNodeNo() {
		return get("node_no");
	}

	public void setNodeName(java.lang.String nodeName) {
		set("node_name", nodeName);
	}

	public java.lang.String getNodeName() {
		return get("node_name");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setApplyUserId(java.lang.Integer applyUserId) {
		set("apply_user_id", applyUserId);
	}

	public java.lang.Integer getApplyUserId() {
		return get("apply_user_id");
	}

	public void setApplyUserName(java.lang.String applyUserName) {
		set("apply_user_name", applyUserName);
	}

	public java.lang.String getApplyUserName() {
		return get("apply_user_name");
	}

	public void setApplyTime(java.lang.Integer applyTime) {
		set("apply_time", applyTime);
	}

	public java.lang.Integer getApplyTime() {
		return get("apply_time");
	}

	public void setApplyOrgId(java.lang.Integer applyOrgId) {
		set("apply_org_id", applyOrgId);
	}

	public java.lang.Integer getApplyOrgId() {
		return get("apply_org_id");
	}

	public void setApplyOrgName(java.lang.String applyOrgName) {
		set("apply_org_name", applyOrgName);
	}

	public java.lang.String getApplyOrgName() {
		return get("apply_org_name");
	}

	public void setIsHasCollateral(java.lang.String isHasCollateral) {
		set("is_has_collateral", isHasCollateral);
	}

	public java.lang.String getIsHasCollateral() {
		return get("is_has_collateral");
	}

	public void setCollateralType(java.lang.String collateralType) {
		set("collateral_type", collateralType);
	}

	public java.lang.String getCollateralType() {
		return get("collateral_type");
	}

	public void setCollateralNo(java.lang.String collateralNo) {
		set("collateral_no", collateralNo);
	}

	public java.lang.String getCollateralNo() {
		return get("collateral_no");
	}

	public void setBelongPartnerId(java.lang.String belongPartnerId) {
		set("belong_partner_id", belongPartnerId);
	}

	public java.lang.String getBelongPartnerId() {
		return get("belong_partner_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
