package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCuProperty<M extends BaseCuProperty<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setCuId(java.lang.String cuId) {
		set("cu_id", cuId);
	}

	public java.lang.String getCuId() {
		return get("cu_id");
	}

	public void setCuName(java.lang.String cuName) {
		set("cu_name", cuName);
	}

	public java.lang.String getCuName() {
		return get("cu_name");
	}

	public void setCertificateType(java.lang.String certificateType) {
		set("certificate_type", certificateType);
	}

	public java.lang.String getCertificateType() {
		return get("certificate_type");
	}

	public void setCertificateNo(java.lang.String certificateNo) {
		set("certificate_no", certificateNo);
	}

	public java.lang.String getCertificateNo() {
		return get("certificate_no");
	}

	public void setBuyTime(java.lang.Integer buyTime) {
		set("buy_time", buyTime);
	}

	public java.lang.Integer getBuyTime() {
		return get("buy_time");
	}

	public void setBuyType(java.lang.String buyType) {
		set("buy_type", buyType);
	}

	public java.lang.String getBuyType() {
		return get("buy_type");
	}

	public void setBuyPrice(java.math.BigDecimal buyPrice) {
		set("buy_price", buyPrice);
	}

	public java.math.BigDecimal getBuyPrice() {
		return get("buy_price");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}

	public java.lang.String getBrand() {
		return get("brand");
	}

	public void setColor(java.lang.String color) {
		set("color", color);
	}

	public java.lang.String getColor() {
		return get("color");
	}

	public void setRunKm(java.math.BigDecimal runKm) {
		set("run_km", runKm);
	}

	public java.math.BigDecimal getRunKm() {
		return get("run_km");
	}

	public void setArea(java.math.BigDecimal area) {
		set("area", area);
	}

	public java.math.BigDecimal getArea() {
		return get("area");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
