package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoanApplyApproveData<M extends BaseLoanApplyApproveData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setLoanApplyId(java.lang.String loanApplyId) {
		set("loan_apply_id", loanApplyId);
	}

	public java.lang.String getLoanApplyId() {
		return get("loan_apply_id");
	}

	public void setLoanCategoryId(java.lang.Integer loanCategoryId) {
		set("loan_category_id", loanCategoryId);
	}

	public java.lang.Integer getLoanCategoryId() {
		return get("loan_category_id");
	}

	public void setDataType(java.lang.String dataType) {
		set("data_type", dataType);
	}

	public java.lang.String getDataType() {
		return get("data_type");
	}

	public void setDataUrl(java.lang.String dataUrl) {
		set("data_url", dataUrl);
	}

	public java.lang.String getDataUrl() {
		return get("data_url");
	}

	public void setAddUserId(java.lang.Integer addUserId) {
		set("add_user_id", addUserId);
	}

	public java.lang.Integer getAddUserId() {
		return get("add_user_id");
	}

	public void setAddUserName(java.lang.String addUserName) {
		set("add_user_name", addUserName);
	}

	public java.lang.String getAddUserName() {
		return get("add_user_name");
	}

	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.Integer getUpdateTime() {
		return get("update_time");
	}

	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	public java.lang.Integer getAddTime() {
		return get("add_time");
	}

}
