package com.dlcat.model;

import com.dlcat.base.BaseCuCorpInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuCorpInfo extends BaseCuCorpInfo<CuCorpInfo> {
	public static final CuCorpInfo dao = new CuCorpInfo().dao();
}
