package com.dlcat.model;

import com.dlcat.base.BaseCuIndInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuIndInfo extends BaseCuIndInfo<CuIndInfo> {
	public static final CuIndInfo dao = new CuIndInfo().dao();
}
