package com.dlcat.model;

import com.dlcat.base.BaseCuObjectCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuObjectCustomer extends BaseCuObjectCustomer<CuObjectCustomer> {
	public static final CuObjectCustomer dao = new CuObjectCustomer().dao();
}
