package com.dlcat.model;

import com.dlcat.base.BaseCuPartners;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuPartners extends BaseCuPartners<CuPartners> {
	public static final CuPartners dao = new CuPartners().dao();
}
