package com.dlcat.model;

import com.dlcat.base.BaseCuProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuProperty extends BaseCuProperty<CuProperty> {
	public static final CuProperty dao = new CuProperty().dao();
}
