package com.dlcat.model;

import com.dlcat.base.BaseFlowData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowData extends BaseFlowData<FlowData> {
	public static final FlowData dao = new FlowData().dao();
}
