package com.dlcat.model;

import com.dlcat.base.BaseFlowObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowObject extends BaseFlowObject<FlowObject> {
	public static final FlowObject dao = new FlowObject().dao();
}
