package com.dlcat.model;

import com.dlcat.base.BaseFlowNode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowNode extends BaseFlowNode<FlowNode> {
	public static final FlowNode dao = new FlowNode().dao();
}
