package com.dlcat.model;

import com.dlcat.base.BaseLoanRepayType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanRepayType extends BaseLoanRepayType<LoanRepayType> {
	public static final LoanRepayType dao = new LoanRepayType().dao();
}
