package com.dlcat.model;

import com.dlcat.base.BaseLoanApplyApprove;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanApplyApprove extends BaseLoanApplyApprove<LoanApplyApprove> {
	public static final LoanApplyApprove dao = new LoanApplyApprove().dao();
}
