package com.dlcat.model;

import com.dlcat.base.BaseRoleBtn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleBtn extends BaseRoleBtn<RoleBtn> {
	public static final RoleBtn dao = new RoleBtn().dao();
}
