package com.dlcat.model;

import com.dlcat.base.BaseSysBtn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysBtn extends BaseSysBtn<SysBtn> {
	public static final SysBtn dao = new SysBtn().dao();
}
