package com.dlcat.model;

import java.util.ArrayList;
import java.util.List;

import com.dlcat.base.BaseSysMenu;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu().dao();
	
	/**
	 * 用于递归查询菜单
	 */
	private List<SysMenu> children=new ArrayList<SysMenu>();

	public List<SysMenu> getChildren() {
		return children;
	}

	public void setChildren(List<SysMenu> children) {
		this.children = children;
	}

	@Override
	public String toString() {
		return super.toString()+"SysMenu [children=" + children + "]";
	}
	/**
	 * 获取用户菜单树，某个节点的一级子节点
	 * @param menuId
	 * @param sysMenu
	 * @return
	 * @author masai
	 * @time 2017年4月16日 下午10:04:56
	 */
	public  List<SysMenu> getFristChildNode(String menuId,SysMenu menuTree){
		SysMenu sm = null;
		for(SysMenu sysMenu : menuTree.getChildren()){
 			sm = queryMenuTreeNode(menuId,sysMenu);
			if(sm != null){
				break;
			}
		}
		return sm == null ? null : sm.getChildren(); 
	}
	/**
	 * 遍历用户菜单树单节点
	 * @param menuId	要查询的menu节点
	 * @param sysMenu	菜单树
	 * @return
	 * @author masai
	 * @time 2017年4月16日 下午9:49:45
	 */
	private  SysMenu queryMenuTreeNode(String menuId,SysMenu sysMenu){
		System.out.println("1111111");
		if(sysMenu.getId() == Integer.parseInt(menuId)){
//			return sysMenu;
			System.out.println("2222222222");
		}
		for(SysMenu sm : sysMenu.getChildren()){
			queryMenuTreeNode(menuId,sm);
		}
		return null;
	}
}
