package com.dlcat.model;

import java.util.List;

import com.dlcat.base.BaseToCodeLibrary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ToCodeLibrary extends BaseToCodeLibrary<ToCodeLibrary> {
	public static final ToCodeLibrary dao = new ToCodeLibrary().dao();
	/**
	 * 根据code_no查询有效字典映射列表
	 * @param codeNo
	 * @return
	 */
	public static List<ToCodeLibrary> getCodeLibrariesByCodeNo(String codeNo) {
		List<ToCodeLibrary> codeLibraries = null;
		if(codeNo != null && !"".equals(codeNo.trim())){
			String sqlString="select * from to_code_library where status=1 and code_no=?";
			codeLibraries = ToCodeLibrary.dao.find(sqlString,codeNo);
		}
		return codeLibraries;
	}
	
	/**
	 * 根据SQL语句查询字典映射列表
	 * @param sql
	 * @return
	 */
	public static List<ToCodeLibrary> getCodeLibrariesBySQL(String sql) {
		List<ToCodeLibrary> codeLibraries=ToCodeLibrary.dao.find(sql);
		return codeLibraries;
	}
}
