package com.dlcat.model;

import java.util.List;

import com.dlcat.base.BaseToCodeLibrary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ToCodeLibrary extends BaseToCodeLibrary<ToCodeLibrary> {
	public static final ToCodeLibrary dao = new ToCodeLibrary().dao();
	/**
	 * 以code_no作为参数查询
	 * @param codeNo
	 * @return
	 */
	public List<ToCodeLibrary> getCodeLibraries(String codeNo) {
		String sqlString="select * from t_code_library where code_no=?";
		List<ToCodeLibrary> codeLibraries=ToCodeLibrary.dao.find(sqlString,codeNo);
		return codeLibraries;
	}
	
	/**
	 * 以SQL语句作为参数查询
	 * @param sql
	 * @return
	 */
	public List<ToCodeLibrary> getCodeLibrariesSQL(String sql) {
		List<ToCodeLibrary> codeLibraries=ToCodeLibrary.dao.find(sql);
		return codeLibraries;
	}
}
