package com.dlcat.model;

import java.util.List;

import com.dlcat.base.BaseToTask;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ToTask extends BaseToTask<ToTask> {
	public static final ToTask dao = new ToTask().dao();
	
	/** 暂停 **/
	public static final int STATE_STOP = 0;
	/** 运行 **/
	public static final int STATE_START = 1;

	public List<ToTask> findAll(){
		return this.find("select * from task");
	}
	
	public List<ToTask> findByStart(){
		return this.find("select * from task where state = 2");
	}
	
	public int updateState(int id, int state){
		return Db.update("update task set state = ? where id = ?", state, id);
}
	}
