package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuCorpInfo extends BaseModel<CuCorpInfo> {
	public static final CuCorpInfo dao = new CuCorpInfo().dao();
}
