package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuIndInfo extends BaseModel<CuIndInfo> {
	public static final CuIndInfo dao = new CuIndInfo().dao();
}
