package com.dlcat.core.model;

import com.dlcat.common.BaseModel;
import com.dlcat.common.utils.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuObjectCustomer extends BaseModel<CuObjectCustomer> {
	public static final CuObjectCustomer dao = new CuObjectCustomer().dao();
	
	/**
	 * 根据id 判断客户是否存在
	 * @author liuran
	 * @time 2017年5月9日 上午10:57:35
	 * @param id  正式客户id
	 * @return boolean (true存在;false不存在)
	 */
	public static boolean isHasCustomer(String id){
		//先判断id是否合法
		if (id.length() == 13 && (id.substring(0, 3).equals("IND")) || (id.substring(0, 3).equals("COR")) ) {
			//判断客户是否存在
			CuObjectCustomer customer = CuObjectCustomer.dao.findById(id);
			if(customer != null){
				return true;
			}
			return false;
		}else {
			return false;
		}	
	}
	/**
	 * 根据id获取用户
	 * @param id
	 * @return
	 * @author masai
	 * @time 2017年5月24日 下午12:01:29
	 */
	public static CuObjectCustomer getCustomerById(String id){
		if(StringUtils.isBlank(id)){
			return null;
		}
		return CuObjectCustomer.dao.findById(id);
	}
	/**
	 * 根据id查询有效客户
	 * @param id
	 * @return	返回null表示不存在或者参数id非法
	 * @author masai
	 * @time 2017年5月24日 上午10:22:44
	 */
	public static CuObjectCustomer getEffectCustomer(String id){
		if(StringUtils.isBlank(id)){
			return null;
		}
		try {
			String sql="select * from cu_object_customer where status='1' and id=?";
			return CuObjectCustomer.dao.findFirst(sql, id);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
