package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuObjectCustomer extends BaseModel<CuObjectCustomer> {
	public static final CuObjectCustomer dao = new CuObjectCustomer().dao();
}
