package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;
import com.sun.org.apache.bcel.internal.generic.Select;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuObjectCustomer extends BaseModel<CuObjectCustomer> {
	public static final CuObjectCustomer dao = new CuObjectCustomer().dao();
	
	/**
	* @author:zhaozhongyuan 
	* @Description: TODO 
	* @param
	* @return List<CuObjectCustomer>
	* @date 2017年4月24日 下午2:54:06  
	*/
	public static List<CuObjectCustomer> getAll() {
		return CuObjectCustomer.dao.find("select * from cu_object_customer");
	}
	
	
	/**
	* @author:zhaozhongyuan 
	* @Description: TODO 
	* @param  sqlIN string
	* @return List<CuObjectCustomer>
	* @date 2017年4月26日 上午9:45:17  
	*/
	public static List<CuObjectCustomer> getCuObjectCustomers(String sqlIN) {
		
		String sql="select * from cu_object_customer where belong_org_id in (?)";
		return CuObjectCustomer.dao.find(sql,sqlIN);
	}
	
	/**
	 * 根据id 判断客户是否存在
	 * @author liuran
	 * @time 2017年5月9日 上午10:57:35
	 * @param id
	 * @return boolean
	 */
	public static boolean isHasCustomer(String id){
		CuObjectCustomer customer = CuObjectCustomer.dao.findById(id);
		if(customer != null){
			return true;
		}
		return false;
	}
	
	
}
