package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuPartners extends BaseModel<CuPartners> {
	public static final CuPartners dao = new CuPartners().dao();
}
