package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuPossibleCustomer extends BaseModel<CuPossibleCustomer> {
	public static final CuPossibleCustomer dao = new CuPossibleCustomer().dao();
}
