package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuProperty extends BaseModel<CuProperty> {
	public static final CuProperty dao = new CuProperty().dao();
}
