package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;
import com.dlcat.common.utils.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuProperty extends BaseModel<CuProperty> {
	public static final CuProperty dao = new CuProperty().dao();

	/**
	 * 押品的证件是否已存在
	 * @author liuran
	 * @time 2017年5月9日 上午11:16:41
	 * @param type 证件类型
	 * @param no 证件编号
	 * @return boolean (true:存在;false:不存在)
	 */
	public static boolean isRepeatCertificate(String type,String no){
		if (StringUtils.isNotBlank(type) && StringUtils.isNotBlank(no)) {
			List<CuProperty> property = CuProperty.dao.find("select * from cu_property where certificate_type = ? and certificate_no = ? ",type,no);
			if(property.size() != 0){
				return true;
			}
			return false;
		}else {
			return false;
		}
		
	}
	/**
	 * 根据用户财产编号，获取财产记录
	 * @param id	抵押物编号
	 * @return	
	 * @author masai
	 * @time 2017年5月24日 上午11:15:47
	 */
	public static CuProperty getPropertyById(String id){
		if(StringUtils.isBlank(id)){
			return null;
		}
		return CuProperty.dao.findById(id);
	}
}
