package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;
import com.dlcat.common.utils.StringUtils;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowData extends BaseModel<FlowData> {
	public static final FlowData dao = new FlowData().dao();
	
	/**
	 * 根据sql语句查询流程数据
	 * @param sql
	 * @return
	 * @author masai
	 * @time 2017年4月26日 上午11:23:47
	 */
	public static  List<FlowData> getFlowDatasBySql(String sql) {
		List<FlowData> datas = FlowData.dao.find(sql);
		return datas;
	}
	
	/**
	 * 根据ID获取数据
	 * @author liuran
	 * @time 2017年4月22日 上午9:43:24
	 * @param id
	 * @return
	 */
	public  static FlowData getFlowDatasById(String id) {
		return StringUtils.isNotBlank(id) ? FlowData.dao.findById(id) : null;
	}
	
	/**
	 * 根据审批流程任务编号查询流程数据
	 */
	public static List<FlowData> getFlowDatasByFlowTaskNo(String flowTaskNo){
		return  StringUtils.isNotBlank(flowTaskNo) ? FlowData.dao.find("select * from flow_data where flow_task_no=?",flowTaskNo) : null;
	}
	
	/**
	 * 根据审批流程对象编号查询流程数据
	 */
	public static List<FlowData> getFlowDatasByFlowObjectNo(String flowObjectNo){
		return StringUtils.isNotBlank(flowObjectNo) ? FlowData.dao.find("select * from flow_data where flow_object_no=?",flowObjectNo) : null;
	}
}
