package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowModel extends BaseModel<FlowModel> {
	public static final FlowModel dao = new FlowModel().dao();
	
	/**
	 * 根据sql 语句查询 流程模型
	 * @param sql
	 * @return
	 * @author masai
	 * @time 2017年4月26日 下午12:08:17
	 */
	public static List<FlowModel> getFlowModelsBySql(String sql) {
		List<FlowModel> datas = FlowModel.dao.find(sql);
		return datas;
	}
	/**
	 * 根据主键获取流程模型
	 * @param id
	 * @return
	 * @author masai
	 * @time 2017年4月26日 下午12:07:34
	 */
	public static FlowModel getFlowModelsById(String id) {
		return FlowModel.dao.findById(id);
	}
}
