package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;
import com.dlcat.common.utils.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowModel extends BaseModel<FlowModel> {
	public static final FlowModel dao = new FlowModel().dao();
	
	/**
	 * 根据sql 语句查询 流程模型
	 * @param sql
	 * @return
	 * @author masai
	 * @time 2017年4月26日 下午12:08:17
	 */
	public static List<FlowModel> getFlowModelsBySql(String sql) {
		List<FlowModel> datas = FlowModel.dao.find(sql);
		return datas;
	}
	/**
	 * 根据主键获取流程模型
	 * @param id
	 * @return
	 * @author masai
	 * @time 2017年4月26日 下午12:07:34
	 */
	public static FlowModel getFlowModelsById(String id) {
		return StringUtils.isNotBlank(id) ? FlowModel.dao.findById(id) : null;
	}
	
	/**
	 * 根据流程类型（借款业务类型）获取有效流程模型
	 * @param flowType	流程类型（借款业务类型）
	 * @return
	 * @author masai
	 * @time 2017年5月2日 下午4:54:01
	 */
	public static FlowModel getFlowModelByFlowType(Integer flowType){
		String sql = "select * from flow_model where status=1 and flow_type=?";
		FlowModel flowModel = null;
		if(flowType != null){
			flowModel = FlowModel.dao.findFirst(sql, flowType);
		}
		return flowModel;
	}
}
