package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowNode extends BaseModel<FlowNode> {
	public static final FlowNode dao = new FlowNode().dao();
}
