package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowObject extends BaseModel<FlowObject> {
	public static final FlowObject dao = new FlowObject().dao();
}
