package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowTask extends BaseModel<FlowTask> {
	public static final FlowTask dao = new FlowTask().dao();
	
	/**
	 * 根据sql语句查询流程任务
	 * @param sql
	 * @return
	 * @author masai
	 * @time 2017年4月26日 上午11:25:42
	 */
	public List<FlowTask> getFlowTasksBySql(String sql) {
		List<FlowTask> datas = FlowTask.dao.find(sql);
		return datas;
	}
	/**
	 * 根据主键查询流程任务
	 * @param taskNo
	 * @return
	 * @author masai
	 * @time 2017年4月26日 上午11:34:33
	 */
	public static FlowTask getFlowTasksById(String taskNo) {
		return FlowTask.dao.findById(taskNo);
	}
	
	/**
	 * 根据流程对象编号和节点编号获取流程任务
	 */
	public static FlowTask getFlowTaskByObjectNoNodeNo(String objectNo,String nodeNo){
		FlowTask tasks=FlowTask.dao.findFirst("select * from flow_task where flow_object_no=? and cur_node_no=? ",objectNo,nodeNo);
		return tasks;
	}
	

}
