package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
/** 
* @author zhaozhongyuan
* @date 2017年4月26日 下午7:33:33 
* @Description: TODO  
*/
@SuppressWarnings("serial")
public class LoanApplyApprove extends BaseModel<LoanApplyApprove>{
	public static final LoanApplyApprove dao = new LoanApplyApprove().dao();
	
}
