package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanBusinessCategory extends BaseModel<LoanBusinessCategory> {
	public static final LoanBusinessCategory dao = new LoanBusinessCategory().dao();
}
