package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanRepayType extends BaseModel<LoanRepayType> {
	public static final LoanRepayType dao = new LoanRepayType().dao();
}
