package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanApplyApproveData extends BaseModel<LoanApplyApproveData> {
	public static final LoanApplyApproveData dao = new LoanApplyApproveData().dao();
}
