package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanProductCategory extends BaseModel<LoanProductCategory> {
	public static final LoanProductCategory dao = new LoanProductCategory().dao();
}
