package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;
import com.dlcat.common.utils.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanApplyApproveData extends BaseModel<LoanApplyApproveData> {
	public static final LoanApplyApproveData dao = new LoanApplyApproveData().dao();
	
	/**
	 * 根据借款申请编号查询借款申请数据
	 * @param loanApplyId	借款申请编号
	 * @return
	 * @author masai
	 * @time 2017年5月2日 下午3:17:44
	 */
	public static List<LoanApplyApproveData> getLoanDateListByApplyId(String loanApplyId){
		String sql = "select * from loan_apply_approve where loan_apply_id=?";
		return	StringUtils.isNotBlank(loanApplyId) ? LoanApplyApproveData.dao.find(sql, loanApplyId) : null;
	}
}
