package com.dlcat.core.model;

import javax.servlet.http.HttpServletRequest;

import com.dlcat.common.BaseModel;
import com.dlcat.common.utils.DateUtil;
import com.dlcat.common.utils.IpUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAdminLog extends BaseModel<SysAdminLog> {
	public static final SysAdminLog dao = new SysAdminLog();
	
	public static void SetAdminLog(SysUser user,String btnID,String data, HttpServletRequest request) {
		SysAdminLog sysAdminLog=new SysAdminLog();
		sysAdminLog.set("Login_id", user.getInt("id"));
		sysAdminLog.set("Login_name", user.getStr("name"));
		sysAdminLog.set("belong_org_id", user.getInt("belong_org_id"));
		sysAdminLog.set("belong_org_name", user.getStr("belong_org_name"));
		sysAdminLog.set("btn_id",btnID);
		sysAdminLog.set("btn_name", SysMenu.getNamebyID(btnID));
		sysAdminLog.set("data", data);
		sysAdminLog.set("createTime",DateUtil.getCurrentTime());
		
		String ip="";
		try {
			ip = IpUtil.getRemoteIp(request);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		sysAdminLog.set("ip", ip);
		sysAdminLog.save();
	}
	
	
}

