package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOrg extends BaseModel<SysOrg> {
	public static final SysOrg dao = new SysOrg().dao();
	
	/**
	 * 获取当前系统中的所有机构 不区分机构状态 
	 * @return
	 * @author masai
	 * @time 2017年4月20日 下午12:18:46
	 */
	public static List<SysOrg> getSysOrgList(){
		String sql = "select * from sys_org";
		return SysOrg.dao.find(sql);
		 
	}
	
	/**
	 * 获取当前机构中所有用户
	 * @return
	 * @author masai
	 * @time 2017年4月21日 上午9:55:53
	 */
	public static List<SysUser> getBelongOrgUser(int orgId){
		String sql = "select * from sys_user where belong_org_id = ?";
		return SysUser.dao.find(sql, orgId);
	}
	/**
	 * 获取当前机构中的所有客户
	 * @param orgId
	 * @return
	 * @author masai
	 * @time 2017年4月21日 上午11:43:21
	 */
	public static List<CuObjectCustomer> getBelongCustomer(int orgId){
		String sql = "select * from cu_object_customer where belong_org_id = ?";
		return CuObjectCustomer.dao.find(sql,orgId);
	}
	
	/**
	* @author:zhaozhongyuan 
	* @Description: 根据机构ID确定层级
	* @param @param orgId
	* @param @return
	* @return int
	* @date 2017年4月24日 下午2:44:10  
	*/
	public static int getLevel(int org_id){
		return SysOrg.dao.findById(org_id).getInt("org_level");
	}
	
}
