package com.dlcat.core.model;

import java.util.List;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseModel<SysRole> {
	public static final SysRole dao = new SysRole().dao();
	
	/**
	 * 获取指定角色下的所有有效用户
	 * @param roleId	角色编号
	 * @return
	 * @author masai
	 * @time 2017年4月21日 下午3:22:05
	 */
	public static List<SysUser> getUserBelongRole(int roleId){
		String sql  = "select * from sys_user where status = '1' role_id = ?";
		return SysUser.dao.find(sql, roleId);
	}
	
	/**
	 * 根据用户id获取用户角色名称
	 */
	public static String getRoleNameByUserId(int userId){
		SysUser user = SysUser.dao.findById(userId);
		String rolename = SysRole.dao.findById(user.getInt("role_id")).getStr("role_name");
		return rolename;
	}
}
