package com.dlcat.core.model;
import java.util.List;

import com.dlcat.common.BaseModel;
import com.jfinal.kit.HashKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseModel<SysUser> {
	public static final SysUser dao = new SysUser().dao();
	
	/**
	 * 所属角色是否合法
	 * time:2017年4月11日 下午2:48:12
	 * @author masai
	 */
	public Boolean isHasRole(){
		return SysRole.dao.findById(this.get("role_id")) != null ? true : false;
	}
	
	/**
	 * 所属机构是否合法
	 * time:2017年4月11日 下午2:47:52
	 * @author masai
	 */
	public Boolean isHasBelongOrg(){
		return SysOrg.dao.findById(this.get("belong_ord_id")) != null ? true : false; 
	}
	
	/**
	 * 获取当前用户的所有管户客户
	 * @param userId 	用户编号 
	 * @return
	 * @author masai
	 * @time 2017年4月21日 上午11:53:35
	 */
	public static List<CuObjectCustomer> getBelongUserList(int userId){
		String sql = "select * from cu_object_customer";
		return CuObjectCustomer.dao.find(sql,userId);
	}
	/**
	 * 根据用户id获取同一机构下相同角色的所有人
	 * @author liuran
	 * @time 2017年4月27日 下午12:31:15
	 * @param userId 
	 * @return List<SysUser>
	 */
	public static List<SysUser> getUserList(int userId){
		SysUser user = SysUser.dao.findById(userId);
		String sql = "select * from sys_user where role_id = ? and belong_org_id = ?";
		List<SysUser> users = SysUser.dao.find(sql,user.getInt("role_id"),user.getInt("belong_org_id"));
		return users;
		
	}
	/**
	 * 判断name除用户本人外 是否存在
	 * @author liuran
	 * @time 2017年5月3日 下午5:44:50
	 * @param name
	 * @return boolean
	 */
	public static boolean isRepeatName(int userId,String name){
		List<SysUser> user = SysUser.dao.find("select * from sys_user where status = '1' and name=? and id !=?",name,userId);
		if (user.size() == 0 ) {
			return false;//昵称不存在 可以使用
		}else {
			return true;
		}
	}
/**
 * 判断手机号除用户本人外 是否存在
 * @author liuran
 * @time 2017年5月3日 下午5:47:09
 * @param phone
 * @return boolean
 */
	public static boolean isRepeatPhone(int userId,String phone){
		List<SysUser> user = SysUser.dao.find("select * from sys_user where status = '1' and phone = ? and id !=?",phone,userId);
		if (user.size() == 0 ) {
			return false;//手机号不存在，可以使用
		}else {
			return true;
		}
	}
	
	/**
	 * 判断用户输入密码是否正确
	 * @author liuran
	 * @time 2017年5月3日 下午5:55:54
	 * @param userId
	 * @param password
	 * @return boolean
	 */
	public static boolean isRightPassword(int userId,String password){
		SysUser user = SysUser.dao.findById(userId);
		if ((user.getStr("password").equals(HashKit.sha1(password)))) {
			return true; //正确
		}else {
			return false;
		}
	}
	
}
