package com.dlcat.core.model;

import com.dlcat.common.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseModel<SysUser> {
	public static final SysUser dao = new SysUser().dao();
	
	/**
	 * 所属角色是否合法
	 * time:2017年4月11日 下午2:48:12
	 * @author masai
	 */
	public Boolean isHasRole(){
		return SysRole.dao.findById(this.get("role_id")) != null ? true : false;
	}
	
	/**
	 * 所属机构是否合法
	 * time:2017年4月11日 下午2:47:52
	 * @author masai
	 */
	public Boolean isHasBelongOrg(){
		return SysOrg.dao.findById(this.get("belong_ord_id")) != null ? true : false; 
	}
	
}
