package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFlowObject<M extends BaseFlowObject<M>> extends Model<M> implements IBean {

	public void setObjectNo(java.lang.String objectNo) {
		set("object_no", objectNo);
	}

	public java.lang.String getObjectNo() {
		return get("object_no");
	}

	public void setObjectName(java.lang.String objectName) {
		set("object_name", objectName);
	}

	public java.lang.String getObjectName() {
		return get("object_name");
	}

	public void setFlowName(java.lang.String flowName) {
		set("flow_name", flowName);
	}

	public java.lang.String getFlowName() {
		return get("flow_name");
	}

	public void setCurrentNodeNo(java.lang.String currentNodeNo) {
		set("current_node_no", currentNodeNo);
	}

	public java.lang.String getCurrentNodeNo() {
		return get("current_node_no");
	}

	public void setCurrentNodeName(java.lang.String currentNodeName) {
		set("current_node_name", currentNodeName);
	}

	public java.lang.String getCurrentNodeName() {
		return get("current_node_name");
	}

	public void setCurrentNodeUserId(java.lang.Integer currentNodeUserId) {
		set("current_node_user_id", currentNodeUserId);
	}

	public java.lang.Integer getCurrentNodeUserId() {
		return get("current_node_user_id");
	}

	public void setCurrentNodeUserName(java.lang.String currentNodeUserName) {
		set("current_node_user_name", currentNodeUserName);
	}

	public java.lang.String getCurrentNodeUserName() {
		return get("current_node_user_name");
	}

	public void setSponsorUserId(java.lang.Integer sponsorUserId) {
		set("sponsor_user_id", sponsorUserId);
	}

	public java.lang.Integer getSponsorUserId() {
		return get("sponsor_user_id");
	}

	public void setSponsorUserName(java.lang.String sponsorUserName) {
		set("sponsor_user_name", sponsorUserName);
	}

	public java.lang.String getSponsorUserName() {
		return get("sponsor_user_name");
	}

	public void setSponsorOrgId(java.lang.String sponsorOrgId) {
		set("sponsor_org_id", sponsorOrgId);
	}

	public java.lang.String getSponsorOrgId() {
		return get("sponsor_org_id");
	}

	public void setSponsorOrgName(java.lang.String sponsorOrgName) {
		set("sponsor_org_name", sponsorOrgName);
	}

	public java.lang.String getSponsorOrgName() {
		return get("sponsor_org_name");
	}

	public void setSponsorTime(java.lang.Integer sponsorTime) {
		set("sponsor_time", sponsorTime);
	}

	public java.lang.Integer getSponsorTime() {
		return get("sponsor_time");
	}

}
