package com.dlcat.model;

import com.dlcat.base.BaseFlowTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowTask extends BaseFlowTask<FlowTask> {
	public static final FlowTask dao = new FlowTask().dao();
}
