package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOrg<M extends BaseSysOrg<M>> extends Model<M> implements IBean {

	public void setOrgId(java.lang.Long orgId) {
		set("org_id", orgId);
	}

	public java.lang.Long getOrgId() {
		return get("org_id");
	}

	public void setSortno(java.lang.Integer sortno) {
		set("sortno", sortno);
	}

	public java.lang.Integer getSortno() {
		return get("sortno");
	}

	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}

	public java.lang.String getOrgName() {
		return get("org_name");
	}

	public void setOrgLevel(java.lang.Integer orgLevel) {
		set("org_level", orgLevel);
	}

	public java.lang.Integer getOrgLevel() {
		return get("org_level");
	}

	public void setOrgTel(java.lang.String orgTel) {
		set("org_tel", orgTel);
	}

	public java.lang.String getOrgTel() {
		return get("org_tel");
	}

	public void setOrgAdd(java.lang.String orgAdd) {
		set("org_add", orgAdd);
	}

	public java.lang.String getOrgAdd() {
		return get("org_add");
	}

	public void setBelongOrgId(java.lang.Integer belongOrgId) {
		set("belong_org_id", belongOrgId);
	}

	public java.lang.Integer getBelongOrgId() {
		return get("belong_org_id");
	}

	public void setBelongOrgName(java.lang.String belongOrgName) {
		set("belong_org_name", belongOrgName);
	}

	public java.lang.String getBelongOrgName() {
		return get("belong_org_name");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setInputUserId(java.lang.Integer inputUserId) {
		set("input_user_id", inputUserId);
	}

	public java.lang.Integer getInputUserId() {
		return get("input_user_id");
	}

	public void setInputUserName(java.lang.String inputUserName) {
		set("input_user_name", inputUserName);
	}

	public java.lang.String getInputUserName() {
		return get("input_user_name");
	}

	public void setInputTime(java.lang.Integer inputTime) {
		set("input_time", inputTime);
	}

	public java.lang.Integer getInputTime() {
		return get("input_time");
	}

	public void setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
	}

	public java.lang.Integer getUpdateUserId() {
		return get("update_user_id");
	}

	public void setUpdateUserName(java.lang.String updateUserName) {
		set("update_user_name", updateUserName);
	}

	public java.lang.String getUpdateUserName() {
		return get("update_user_name");
	}

	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.Integer getUpdateTime() {
		return get("update_time");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
