package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFlowNode<M extends BaseFlowNode<M>> extends Model<M> implements IBean {

	public void setNodeNo(java.lang.String nodeNo) {
		set("node_no", nodeNo);
	}

	public java.lang.String getNodeNo() {
		return get("node_no");
	}

	public void setNodeName(java.lang.String nodeName) {
		set("node_name", nodeName);
	}

	public java.lang.String getNodeName() {
		return get("node_name");
	}

	public void setNodeSortOrder(java.lang.Integer nodeSortOrder) {
		set("node_sort_order", nodeSortOrder);
	}

	public java.lang.Integer getNodeSortOrder() {
		return get("node_sort_order");
	}

	public void setFlowId(java.lang.String flowId) {
		set("flow_id", flowId);
	}

	public java.lang.String getFlowId() {
		return get("flow_id");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
