package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFlowModel<M extends BaseFlowModel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setFlowType(java.lang.String flowType) {
		set("flow_type", flowType);
	}

	public java.lang.String getFlowType() {
		return get("flow_type");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setInputTime(java.lang.Integer inputTime) {
		set("input_time", inputTime);
	}

	public java.lang.Integer getInputTime() {
		return get("input_time");
	}

	public void setInputUserId(java.lang.Integer inputUserId) {
		set("input_user_id", inputUserId);
	}

	public java.lang.Integer getInputUserId() {
		return get("input_user_id");
	}

	public void setInputOrgId(java.lang.String inputOrgId) {
		set("input_org_id", inputOrgId);
	}

	public java.lang.String getInputOrgId() {
		return get("input_org_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
