package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCuIndInfo<M extends BaseCuIndInfo<M>> extends Model<M> implements IBean {

	public void setCuIndId(java.lang.String cuIndId) {
		set("cu_ind_id", cuIndId);
	}

	public java.lang.String getCuIndId() {
		return get("cu_ind_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}

	public java.lang.String getGender() {
		return get("gender");
	}

	public void setCardId(java.lang.String cardId) {
		set("card_id", cardId);
	}

	public java.lang.String getCardId() {
		return get("card_id");
	}

	public void setBornDate(java.lang.Integer bornDate) {
		set("born_date", bornDate);
	}

	public java.lang.Integer getBornDate() {
		return get("born_date");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setWechat(java.lang.String wechat) {
		set("wechat", wechat);
	}

	public java.lang.String getWechat() {
		return get("wechat");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setEdu(java.lang.String edu) {
		set("edu", edu);
	}

	public java.lang.String getEdu() {
		return get("edu");
	}

	public void setMarriageStatus(java.lang.Integer marriageStatus) {
		set("marriage_status", marriageStatus);
	}

	public java.lang.Integer getMarriageStatus() {
		return get("marriage_status");
	}

	public void setChildsCount(java.lang.Integer childsCount) {
		set("childs_count", childsCount);
	}

	public java.lang.Integer getChildsCount() {
		return get("childs_count");
	}

	public void setResidenceAddr(java.lang.String residenceAddr) {
		set("residence_addr", residenceAddr);
	}

	public java.lang.String getResidenceAddr() {
		return get("residence_addr");
	}

	public void setLiveAddr(java.lang.String liveAddr) {
		set("live_addr", liveAddr);
	}

	public java.lang.String getLiveAddr() {
		return get("live_addr");
	}

	public void setWorkConpanyType(java.lang.String workConpanyType) {
		set("work_conpany_type", workConpanyType);
	}

	public java.lang.String getWorkConpanyType() {
		return get("work_conpany_type");
	}

	public void setWorkConpanySize(java.lang.Integer workConpanySize) {
		set("work_conpany_size", workConpanySize);
	}

	public java.lang.Integer getWorkConpanySize() {
		return get("work_conpany_size");
	}

	public void setWorkName(java.lang.String workName) {
		set("work_name", workName);
	}

	public java.lang.String getWorkName() {
		return get("work_name");
	}

	public void setWorkAddr(java.lang.String workAddr) {
		set("work_addr", workAddr);
	}

	public java.lang.String getWorkAddr() {
		return get("work_addr");
	}

	public void setIsHasSsc(java.lang.String isHasSsc) {
		set("is_has_ssc", isHasSsc);
	}

	public java.lang.String getIsHasSsc() {
		return get("is_has_ssc");
	}

	public void setWorkBusiness(java.lang.String workBusiness) {
		set("work_business", workBusiness);
	}

	public java.lang.String getWorkBusiness() {
		return get("work_business");
	}

	public void setMeonthIncome(java.math.BigDecimal meonthIncome) {
		set("meonth_income", meonthIncome);
	}

	public java.math.BigDecimal getMeonthIncome() {
		return get("meonth_income");
	}

	public void setWorkPhone(java.lang.String workPhone) {
		set("work_phone", workPhone);
	}

	public java.lang.String getWorkPhone() {
		return get("work_phone");
	}

	public void setRelativeName(java.lang.String relativeName) {
		set("relative_name", relativeName);
	}

	public java.lang.String getRelativeName() {
		return get("relative_name");
	}

	public void setRelativeShip(java.lang.String relativeShip) {
		set("relative_ship", relativeShip);
	}

	public java.lang.String getRelativeShip() {
		return get("relative_ship");
	}

	public void setRelativePhone(java.lang.String relativePhone) {
		set("relative_phone", relativePhone);
	}

	public java.lang.String getRelativePhone() {
		return get("relative_phone");
	}

	public void setRelativeAddr(java.lang.String relativeAddr) {
		set("relative_addr", relativeAddr);
	}

	public java.lang.String getRelativeAddr() {
		return get("relative_addr");
	}

	public void setRelativeWorkAddr(java.lang.String relativeWorkAddr) {
		set("relative_work_addr", relativeWorkAddr);
	}

	public java.lang.String getRelativeWorkAddr() {
		return get("relative_work_addr");
	}

}
