package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFlowData<M extends BaseFlowData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setFlowObjectNo(java.lang.String flowObjectNo) {
		set("flow_object_no", flowObjectNo);
	}

	public java.lang.String getFlowObjectNo() {
		return get("flow_object_no");
	}

	public void setFlowTaskNo(java.lang.String flowTaskNo) {
		set("flow_task_no", flowTaskNo);
	}

	public java.lang.String getFlowTaskNo() {
		return get("flow_task_no");
	}

	public void setDataType(java.lang.String dataType) {
		set("data_type", dataType);
	}

	public java.lang.String getDataType() {
		return get("data_type");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	public java.lang.Integer getAddTime() {
		return get("add_time");
	}

	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.Integer getUpdateTime() {
		return get("update_time");
	}

}
