package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCuPartners<M extends BaseCuPartners<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setContactInfo(java.lang.String contactInfo) {
		set("contact_info", contactInfo);
	}

	public java.lang.String getContactInfo() {
		return get("contact_info");
	}

	public void setInputTime(java.lang.Integer inputTime) {
		set("input_time", inputTime);
	}

	public java.lang.Integer getInputTime() {
		return get("input_time");
	}

	public void setInputOrgId(java.lang.Integer inputOrgId) {
		set("input_org_id", inputOrgId);
	}

	public java.lang.Integer getInputOrgId() {
		return get("input_org_id");
	}

	public void setInpuOrgName(java.lang.String inpuOrgName) {
		set("inpu_org_name", inpuOrgName);
	}

	public java.lang.String getInpuOrgName() {
		return get("inpu_org_name");
	}

	public void setInputUserId(java.lang.Integer inputUserId) {
		set("input_user_id", inputUserId);
	}

	public java.lang.Integer getInputUserId() {
		return get("input_user_id");
	}

	public void setInputUserName(java.lang.String inputUserName) {
		set("input_user_name", inputUserName);
	}

	public java.lang.String getInputUserName() {
		return get("input_user_name");
	}

	public void setBelongOrgId(java.lang.Integer belongOrgId) {
		set("belong_org_id", belongOrgId);
	}

	public java.lang.Integer getBelongOrgId() {
		return get("belong_org_id");
	}

	public void setBelongOrgName(java.lang.String belongOrgName) {
		set("belong_org_name", belongOrgName);
	}

	public java.lang.String getBelongOrgName() {
		return get("belong_org_name");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
