package com.dlcat.model;

import com.dlcat.base.BaseLoanApplyApproveData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanApplyApproveData extends BaseLoanApplyApproveData<LoanApplyApproveData> {
	public static final LoanApplyApproveData dao = new LoanApplyApproveData().dao();
}
