package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}

	public java.lang.String getRoleName() {
		return get("role_name");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setInputUserId(java.lang.Integer inputUserId) {
		set("input_user_id", inputUserId);
	}

	public java.lang.Integer getInputUserId() {
		return get("input_user_id");
	}

	public void setInputUserName(java.lang.String inputUserName) {
		set("input_user_name", inputUserName);
	}

	public java.lang.String getInputUserName() {
		return get("input_user_name");
	}

	public void setInputOrgId(java.lang.Integer inputOrgId) {
		set("input_org_id", inputOrgId);
	}

	public java.lang.Integer getInputOrgId() {
		return get("input_org_id");
	}

	public void setInputOrgName(java.lang.String inputOrgName) {
		set("input_org_name", inputOrgName);
	}

	public java.lang.String getInputOrgName() {
		return get("input_org_name");
	}

	public void setInputTime(java.lang.Integer inputTime) {
		set("input_time", inputTime);
	}

	public java.lang.Integer getInputTime() {
		return get("input_time");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
