package com.dlcat.model;

import com.dlcat.base.BaseTCodeLibrary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TCodeLibrary extends BaseTCodeLibrary<TCodeLibrary> {
	public static final TCodeLibrary dao = new TCodeLibrary().dao();
}
