package com.dlcat.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoanBusinessCategory<M extends BaseLoanBusinessCategory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setAmountMin(java.math.BigDecimal amountMin) {
		set("amount_min", amountMin);
	}

	public java.math.BigDecimal getAmountMin() {
		return get("amount_min");
	}

	public void setAmountMax(java.math.BigDecimal amountMax) {
		set("amount_max", amountMax);
	}

	public java.math.BigDecimal getAmountMax() {
		return get("amount_max");
	}

	public void setAprMin(java.math.BigDecimal aprMin) {
		set("apr_min", aprMin);
	}

	public java.math.BigDecimal getAprMin() {
		return get("apr_min");
	}

	public void setAprMax(java.math.BigDecimal aprMax) {
		set("apr_max", aprMax);
	}

	public java.math.BigDecimal getAprMax() {
		return get("apr_max");
	}

	public void setPeriodMin(java.lang.Integer periodMin) {
		set("period_min", periodMin);
	}

	public java.lang.Integer getPeriodMin() {
		return get("period_min");
	}

	public void setPeriodMax(java.lang.Integer periodMax) {
		set("period_max", periodMax);
	}

	public java.lang.Integer getPeriodMax() {
		return get("period_max");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
