package com.dlcat.model;

import com.dlcat.base.BaseSysOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOrg extends BaseSysOrg<SysOrg> {
	public static final SysOrg dao = new SysOrg().dao();
}
