package com.dlcat.model;

import com.dlcat.base.BaseLoanProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanProductCategory extends BaseLoanProductCategory<LoanProductCategory> {
	public static final LoanProductCategory dao = new LoanProductCategory().dao();
}
