package com.dlcat.model;

import com.dlcat.base.BaseFlowModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowModel extends BaseFlowModel<FlowModel> {
	public static final FlowModel dao = new FlowModel().dao();
}
